
version: '3.8'
services:
  mssqldb:
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: "Y"
    volumes: 
      - mssqldb:/data
volumes:
  mssqldb:
    driver: local
